- REQUIRE
- src/Optim.jl
- src/cg.jl
- src/fminbox.jl
- src/levenberg_marquardt.jl
- src/linesearch/hz_linesearch.jl
- src/nnls.jl
- src/problems/unconstrained.jl
Using Compat this time for dictionary constructions.
Tests pass for me sans warnings on the 0.3.4 release and the master.
[nan and inf deprecated](https://github.com/JuliaLang/julia/pull/8776)
[iceil merged into ceil](https://github.com/JuliaLang/julia/pull/9133)
> Fix deprecated functions/syntax for Julia 0.4

- src/linesearch/hz_linesearch.jl
If an incorrect or absent gradient or Hessian is given, hz_linesearch
will sometimes error out with "assertion failed: dphia < 0." This commit
supplies a more informative error message suggesting that the user's
gradient or Hessian may be wrong.
> Improve error messages in hz_linesearch

- src/problems/unconstrained.jl
- test/cg.jl
- test/nelder_mead.jl
- test/newton.jl
PR as a follow-up to https://github.com/JuliaOpt/Optim.jl/pull/101 where I messed up the git history
> Added problem hessians and tests

- src/Optim.jl
- src/accelerated_gradient_descent.jl
- src/bfgs.jl
- src/brent.jl
- src/cg.jl
- src/fminbox.jl
- src/golden_section.jl
- src/gradient_descent.jl
- src/l_bfgs.jl
- src/levenberg_marquardt.jl
- src/momentum_gradient_descent.jl
- src/nelder_mead.jl
- src/newton.jl
- src/optimize.jl
- src/simulated_annealing.jl
- src/utilities/update.jl
- test/callbacks.jl
- test/runtests.jl
This is the pull request discussed in #130. 
It allows for having callback functions without breaking the existing interface
First of all it introduced the `show_every` param (defaults to 1) which controls for how regularly traces are shown and callbacks are called.
`show_trace` is unaffected except the `show_every` influence and one detail: If a callback is given then setting `extended_trace` to true will not automatically set `show_trace` to true as well. This is such that you can have a callback that has access to the extended stuff without having to have the console spam of `show_trace`. Using the interface as it was before this PR yields same results as before.
Callbacks are implemented for all models but `fminbox` and `levenberg_marquar` since they are special in the show_trace …
> implemented callback functions

- src/levenberg_marquardt.jl
Three changes
- sse is replaced by sumabs2
- sqrt(lambda) is replaced by lambda^2. I think it's a typo in the original implementation.
- lambda is diminished only if rho is close to one. This seems to be the standard for levenberg_marquardt
> changes in levenberg_marquardt

- src/l_bfgs.jl
A call to the removed `_dot` method was left in the L-BFGS code. This fixes it.
> Fix remaining call to _dot

- test/brent.jl
- test/callbacks.jl
- test/gradient_descent.jl
- test/nelder_mead.jl
- test/newton.jl
- test/simulated_annealing.jl
This gets tests passing on 0.5.
> fixes for 0.5 function changes

- src/levenberg_marquardt.jl
- test/levenberg_marquardt.jl
also adds a tab -> space. For no whitespace diff: https://github.com/KristofferC/Optim.jl/commit/41a8eb3906da81af693203815cb0d60c644ef5bf?w=1
Confirmed that LsqFit passes after this. We should have a in repo test for this as well but I am a bit short of time now.
> fix wrong length in buffers in LM

- REQUIRE
- src/Optim.jl
- src/newton.jl
- test/newton.jl
I have no idea where I pulled the other request from in #123 . Made a branch here instead.
```julia
julia> using Optim
julia> prob=Optim.UnconstrainedProblems.examples["Himmelblau"]
Optim.UnconstrainedProblems.OptimizationProblem("Himmelblau",Optim.UnconstrainedProblems.himmelblau,Optim.UnconstrainedProblems.himmelblau_gradient!,Optim.UnconstrainedProblems.himmelblau_hessian!,[2.0,2.0],[3.0,2.0],true,true)
julia> ddf = TwiceDifferentiableFunction(prob.f, prob.g!,prob.h!)
Optim.TwiceDifferentiableFunction(Optim.UnconstrainedProblems.himmelblau,Optim.UnconstrainedProblems.himmelblau_gradient!,fg!,Optim.UnconstrainedProblems.himmelblau_hessian!)
julia> res = optimize(ddf, [0., 0.], ModifiedNewton())
Results of Optimization Algorithm
* Algorithm: Modified Newton's Method
* Starting Point: …
```
> Modified Newton using PositiveFactorizations

- src/Optim.jl
- src/cg.jl
- src/deprecate.jl
- src/fminbox.jl
- src/gradient_descent.jl
- src/l_bfgs.jl
- src/precon.jl
- test/precon.jl
- test/runtests.jl
This was discussed in [Issue 188](https://github.com/JuliaOpt/Optim.jl/issues/188).
* created `precon.jl`
* added preconditioning to `GradientDescent` and to `LBFGS`
* added `test/precon.jl` to test preconditioning capabilities
* added a matrix preconditioner
Documentation has been added in a separate [pull request #190 ](https://github.com/JuliaOpt/Optim.jl/pull/190).
I think this is just a quick and dirty implementation. I suggest more 
substantial changes in this direction in [Issue 188](https://github.com/JuliaOpt/Optim.jl/issues/188).
> Modifications and Extension of Preconditioning

- src/brent.jl
It seems like a mistake to compare `x_new` with `x_minimum_old` etc. in order to decide whether it is a better minimiser. I assume it was meant to be a comparison between `f_new` and `f_minimum_old` etc.
> Control flow check values of f_ instead of x_

- src/accelerated_gradient_descent.jl
- src/bfgs.jl
- src/cg.jl
- src/gradient_descent.jl
- src/l_bfgs.jl
- src/linesearch/hz_linesearch.jl
- src/momentum_gradient_descent.jl
- src/newton.jl
- src/utilities/assess_convergence.jl
- src/utilities/history.jl
A step towards restoring matrix input. I'm not sure if these were always formulated like this, but then the traced gradient has been the matrix norm, not the largest absolute value .
```jlcon
julia> A=rand(3,3)
3x3 Array{Float64,2}:
0.336186  0.542031  0.82909 
0.514256  0.872448  0.731126
0.548907  0.672507  0.774536
julia> norm(A,Inf)
2.1178290608602834
julia> vecnorm(A, Inf)
0.8724475596453296
julia> a = rand(3,1)
3x1 Array{Float64,2}:
0.0691116
0.730404 
0.3318   
julia> norm(a, Inf)
0.7304037281211753
```
> Fix norm -> vecnorm.

- README.md
- src/fminbox.jl
- test/constrained.jl
Fixes #89 
Trying to clean up the issues, I stumbled upon #89 . This PR fixes the "keyword" issues where "eta" and the preconditioner-keywords were forced into the optimizer constructors. This enables 
```
results = Optim.optimize(objective, x0, l, u, Fminbox(), optimizer = LBFGS)
``` 
which will be preconditioned due to the recent refactoring + improvement of preconditioning, but also
```
results = Optim.optimize(objective, x0, l, u, Fminbox(), optimizer = BFGS)
``` 
or even
```
results = Optim.optimize(objective, x0, l, u, Fminbox(), optimizer = NelderMead)
``` 
You might not want to do it, but currently, all the methods in Optim should be passable, although Newton will generate a warning and default to CG.
> Generalize box constrained optimization slightly.

- README.md
- src/cg.jl
- src/fminbox.jl
- src/gradient_descent.jl
- src/l_bfgs.jl
- src/precon.jl
- test/precon.jl
This uses only method that are available in base and hence can be easily overloaded without needing to import anything from `Optim.jl`.  The main "conceptual change" is that `P` now described the matrix and not its inverse. This is good for consistency with the iterative linear algebra packages.
A few specific items to consider when reviewing:
* `Base.A_ldiv_B!(x, P::AbstractMatrix, b)` is not implemented in Base, though there is a pull request for it. I now added it to precon.jl, but will remove it once it is no longer necessary.
* I kept the name `precondprep!` for the sake of history, though was tempted to replace it with `updateP!`, which I think is more descriptive. (but no big deal)\
* for the diagonal preconditions I replaced SIMD loops with standard vectorised instructions. I just …
> Re-implemented Preconditioning

- src/Optim.jl
- src/optimize.jl
- src/particle_swarm.jl
- test/particle_swarm.jl
- test/runtests.jl
implementation of the adaptive particle swarm algorithm which is a global optimization method.
tested this algorithm on many real world problems. although being slower than
the gradient based versions it proves stable, especially for systems with "real" data
which can be noisy or in other ways hampered.
I tried my best to have the code in similar form as the other packages in Optim.jl, but surely there
is a lot of room for improvement.
No optimization for speed done yet.
My first PR, so go easy on my ;)
> particle_swarm

- src/types.jl
- test/types.jl
I tried to access `trace[end]` in some code and ran into this error. I opened a PR since I don't see any reason to not add this.
> Define endof for OptimizationTrace

- docs/src/algo/nelder_mead.md
- src/nelder_mead.jl
- test/nelder_mead.jl
- test/types.jl
#105 #110 proposed doing what Gao and Han (2010) [DOI 10.1007/s10589-010-9329-3] proposed, namely adjusting the parameters in Nelder-Mead according to the dimensionality of the problem. Basically, it avoids too many reflections, and tries to bias the steps towards expansion and contraction steps. This is based on the fact that, at least for (uniformly) convex functions, they have a sufficient descent property, even if this property diminishes as the dimensionality diverges to infinity.
This PR revives the other PR, and finishes it. It brings quite severe performance improvements with it. The old unconstrained test problem set is done in about 0.007 seconds, and allocates 1.77 MB of memory. To compare, the current master NelderMead finishes in about 0.8-0.9 seconds and allocates a bit more …
> [RFC] Implement adaptive parameters version of Nelder-Mead.

- src/levenberg_marquardt.jl
- test/levenberg_marquardt.jl
clamping the search space drastically improves the fit in my use case, and prevents `SingularException`s being thrown.
while at it i also reformatted the docs to conform to current guidelines.
> added bounds argument to levenberg_marquardt

- src/accelerated_gradient_descent.jl
- src/api.jl
- src/bfgs.jl
- src/brent.jl
- src/cg.jl
- src/golden_section.jl
- src/gradient_descent.jl
- src/l_bfgs.jl
- src/levenberg_marquardt.jl
- src/momentum_gradient_descent.jl
- src/nelder_mead.jl
- src/newton.jl
- src/newton_trust_region.jl
- src/particle_swarm.jl
- src/simulated_annealing.jl
- src/types.jl
- test/callbacks.jl
- test/newton_trust_region.jl
- test/types.jl
Here is a sketch of how I would implement `OptimizationTrace`. I didn't add any new tests, but it looks like the appropriate checks are already in place.
The only thing that is slightly funky is that `optimize` end up initializing the `OptimizationTrace` like this:
```julia
mo = NelderMead()
OptimizationTrace{typeof(mo)}()
```
There might be something more elegant, but this seems okay to me at least. Let me know your thoughts.
> Simplify OptimizationTrace as a Vector{T<:OptimizationState}

- src/levenberg_marquardt.jl
- test/levenberg_marquardt.jl
this fixes a bug which crept in recently when using `show_trace=true` in levenberg_marquardt.
> fixed levenberg_marquardt/show_trace crash

- src/fminbox.jl
- src/linesearch/hz_linesearch.jl
Currently, Fminbox calls df.fg! on line 158, but never uses the resulting function evaluation. I've just changed the code to only store the gradient information.
> Small cleanup of fminbox code

- src/newton_trust_region.jl
- test/newton_trust_region.jl
This PR adds unit tests for `solve_tr_subproblem!` based on randomly generated Hessians and gradients. For some indefinite Hessians, the tests fail.
This PR also includes a fix: `lambda_lb` does not need to be so large. With large values of `lambda_lb`, the trust region method finds interior solutions to the quadratic minimization problem when it should find a boundary solution. All tests pass with a smaller value for `lambda_lb`.
I've also verified that the fix doesn't break anything in the Celeste.jl package, which depends on the newton trust region code in Optim.jl, and may call `solve_tr_subproblem!` with Hessians that are more poorly conditioned than the Hessians these new unit tests generate at random.
> Fixes solve_tr_subproblem!

- docs/src/index.md
After some previous discussion (see closed pull request "Concerning optimisation of univariate functions using bracketing methods - Documentation #296"), some people suggested that it may be useful to those not familiar with optimisation in general, to add a brief comment saying that the Optim package provides solver that will find local optima and cannot be used to locate a global optimum.
I have added now inserted such a brief comment. Let me know what you think, cheers.
> Update index.md - Following discussion on "Concerning optimisation of univariate functions using bracketing methods"

- src/types.jl
This makes `show(results)` do not print a newline character at the end:
```
julia> r = optimize(rosenbrock, zeros(2))
Results of Optimization Algorithm
* Algorithm: Nelder-Mead
* Starting Point: [0.0,0.0]
* Minimizer: [1.0000879002056393,1.0001763875092962]
* Minimum: 7.760013e-09
* Iterations: 74
* Convergence: true
*  √(Σ(yᵢ-ȳ)²)/n < 1.0e-08: true
* Reached Maximum Number of Iterations: false
* Objective Function Calls: 108
julia> r = optimize(rosenbrock, zeros(2), BFGS())
Results of Optimization Algorithm
* Algorithm: BFGS
* Starting Point: [0.0,0.0]
* Minimizer: [0.9999999929485311,0.9999999859278653]
* Minimum: 4.981810e-17
* Iterations: 21
* Convergence: true
* |x - x'| < 1.0e-32: false
* |f(x) - f(x')| / |f(x)| < 1.0e-32: true
* |g(x)| < 1.0e-08: false
* Reached Maximum Number of …
```
> tweak showing optimization results

- .travis.yml
Currently tests aren't run on nightly so this can break downstream packages (like Gadfly)
> Test on nightly

- NEWS.md
- REQUIRE
- src/accelerated_gradient_descent.jl
- src/bfgs.jl
- src/cg.jl
- src/gradient_descent.jl
- src/l_bfgs.jl
- src/momentum_gradient_descent.jl
- src/newton.jl
- test/lsthrow.jl
- test/runtests.jl
I've just added this as a WIP proposal for how to treat linesearch errors, to add to #263. Probably no reason to fully develop this until #266  is sorted.
I'm using this at the moment to get around the Error throw, as I'm only calling Optim in an inner loop of a solve that does not require very high tolerance.
TODO:
> RFC: catch linesearch errors

- src/nelder_mead.jl
- src/utilities/assess_convergence.jl
- src/utilities/trace.jl
- test/api.jl
- test/nelder_mead.jl
This pull request is intended to fix the tracing for Nelder-Mead algorithm. Currently, `show_trace` for Nelder-Mead is showing the same function values for all iterations because `state.f_lowest` is not updated. In addition to the fix of this bug, I have updated the variable names as suggested in this comment.
> f_x and f_x_previous should be renamed to nm_x, nm_x_previous and f_x should hold
-# f_lowest instead!
On a side note, `f_lowest` and `f_x` should hold the same values during the iterations, but I am updating only `f_lowest` by following how `trace!` is currently implemented. I have also removed `f_x_previous` because it was not used.
I hope this update reflects the intention of the comment.
> Fix some bugs of the tracing for Nelder-Mead algorithm.

- src/accelerated_gradient_descent.jl
- src/l_bfgs.jl
- src/nelder_mead.jl
- src/particle_swarm.jl
- src/simulated_annealing.jl
- src/utilities/generic.jl
This is usually a good idea for handling Win32 since it fixes the issue that
```julia
type A
a::Int64
end 
A(1)
```
throws an error, and 
```julia
f(i::Int64) = 2
f(1)
```
throw an error on 32-bit systems. Given the changes that were made, it seems this may be all that's needed to fix Win32, but AppVeyor will be the one to let us know.
Could potentially fix https://github.com/JuliaOpt/Optim.jl/issues/332
> Remove Int64

- NEWS.md
- docs/src/algo/lbfgs.md
- docs/src/algo/newton.md
- src/bfgs.jl
- src/newton.jl
- test/api.jl
- test/newton.jl
Resetting the initial step for the linesearch to one after each iteration in Newton and BFGS improves convergence: 
Newton CUTEst tests with maxvar = 5:
BFGS CUTEst tests with maxvar = 5:
BT3 is backtracking with cubic interpolation, added in anriseth/LineSearches.jl#20. The behaviour for quadratic bactracking is similar.
LBFGS already has a variant of this implemented, so I haven't added it there.
Ref #91
> BFGS and Newton: reset initial linesearch step to one

- test/REQUIRE
- test/accelerated_gradient_descent.jl
- test/api.jl
- test/array.jl
- test/bfgs.jl
- test/brent.jl
- test/callbacks.jl
- test/cg.jl
- test/constrained.jl
- test/extrapolate.jl
- test/golden_section.jl
- test/gradient_descent.jl
- test/grid_search.jl
- test/initial_convergence.jl
- test/l_bfgs.jl
- test/levenberg_marquardt.jl
- test/lsthrow.jl
- test/momentum_gradient_descent.jl
- test/nelder_mead.jl
- test/newton.jl
- test/newton_trust_region.jl
- test/optimize.jl
- test/particle_swarm.jl
- test/precon.jl
- test/runtests.jl
- test/simulated_annealing.jl
- test/type_stability.jl
- test/types.jl
Just something I've been wanting to do for some time. I think we should also move all the identical loops over problems into the `optimize` test set, and let individual files for each solver be there only if we have unit tests for related methods or very specific problems. NewtonTrustRegion is a perfect example with tests for the subproblem solver.
> Change all tests to testsets and suppress some information by default.

- src/newton_trust_region.jl
- test/newton_trust_region.jl
This PR fixes a bug in `newton_trust_region.jl`. In the loop around line 128, we want to increment lambda by 1% of the **difference** between the largest and smallest eigenvalues. Without this PR, we're effectively incrementing lambda by 1% of the **sum** of the largest and smallest eigenvalues.   That can lead to a `Base.LinAlg.PosDefException(5)` later in the code if the algebraically smallest eigenvalue is larger in magnitude than the algebraically largest eigenvalue, as reported by @rgiordan in jeff-regier/Celeste.jl#529
> bug fix for newton_trust_region

- src/levenberg_marquardt.jl
- src/optimize.jl
I fixed a warning that came up with Optim on v0.6:
```jl
WARNING: Method definition optimize(Any, Array{T, N} where N, M<:Optim.Optimizer, Optim.Options{TCallback} where TCallback<:Union{Void, Function}) in module Optim at /home/riseth/.julia/v0.6/Optim/src/optimize.jl:52 overwritten at /home/riseth/.julia/v0.6/Optim/src/optimize.jl:169.
```
In addition, I removed lots of Levenberg deprecation warnings that cluttered up the test output. I guess we should just remove the Levenberg code at some point?
> v0.6 warning fixes

- docs/src/dev/contributing.md
- docs/src/user/minimization.md
- src/accelerated_gradient_descent.jl
- src/bfgs.jl
- src/cg.jl
- src/gradient_descent.jl
- src/l_bfgs.jl
- src/momentum_gradient_descent.jl
- src/nelder_mead.jl
- src/newton.jl
- src/newton_trust_region.jl
- src/particle_swarm.jl
- src/simulated_annealing.jl
- src/utilities/generic.jl
- test/array.jl
Pulled out from #337. Adds a note in the docs and tests for Vector, Matrix and `Array{T, 3}`. fixes #198 
Extra lines added are docs and tests. Most of this is just reparameterization/use of `similar`.
> Reintroduce generic Array inputs.

- src/utilities/trace.jl
- test/particle_swarm.jl
- test/simulated_annealing.jl
In unrelated work I made mistake in renaming variable names, and the error didn't show up because we didn't run these two with tracing on at any point.
> Clean trace for SimulatedAnnealing and ParticleSwarm.

- src/accelerated_gradient_descent.jl
- test/accelerated_gradient_descent.jl
AcceleratedGradientDescent updated f and g before `update_g!` did, so it converged instantly in `f` according to `assess_convergence`
> Fix AcceleratedGradientDescent f-checks.

- REQUIRE
The latest version of ForwardDiff is needed to support Julia v0.6 without deprecation warnings, but it drops v0.4 support. Since bumping the lower bound here would mean dropping v0.4 support from Optim, I only bumped the upper bound.
> bump ForwardDiff version upper bound

- src/multivariate/solvers/first_order/accelerated_gradient_descent.jl
- src/multivariate/solvers/first_order/bfgs.jl
- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
- src/multivariate/solvers/first_order/l_bfgs.jl
- src/multivariate/solvers/first_order/momentum_gradient_descent.jl
In all the first order methods I've simply removed the requirement that a `linesearch!` must be a function. This allows to plug in a type, which can be made callable. That will allow for a smooth transition from line search functions to line search types. 
In a second step, one can introduce a type `AbstractLinesearch` in `Linesearches.jl`, and then `linesearch!` could be made a `Union{Function, AbstractLinesearch}`. But I'd leave this as a second step, or even remove the possibility of it being a function altogether.
CC @pkofod  , @anriseth
> Prepare for a Switching LineSearches.jl to dispatch

- src/utilities/trace.jl
- src/utilities/update.jl
- test/multivariate/solvers/zeroth_order/nelder_mead.jl
I was using the Nelder-Mead solver and the trace was only storing the final value. This was because the solver was reusing memory. This small changes fixes the issue.
> Use copy when storing Nelder-Mead trace

- src/Optim.jl
- src/multivariate/solvers/first_order/bfgs.jl
- src/multivariate/solvers/first_order/l_bfgs.jl
- src/multivariate/solvers/zeroth_order/particle_swarm.jl
- test/multivariate/array.jl
> Fix input for (L)BFGS and PSO

- src/multivariate/solvers/first_order/accelerated_gradient_descent.jl
- src/multivariate/solvers/first_order/bfgs.jl
- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
- src/multivariate/solvers/first_order/l_bfgs.jl
- src/multivariate/solvers/first_order/momentum_gradient_descent.jl
- src/multivariate/solvers/second_order/newton.jl
- src/multivariate/solvers/second_order/newton_trust_region.jl
- src/multivariate/solvers/zeroth_order/nelder_mead.jl
- src/multivariate/solvers/zeroth_order/particle_swarm.jl
- src/multivariate/solvers/zeroth_order/simulated_annealing.jl
- src/utilities/assess_convergence.jl
- src/utilities/trace.jl
- test/multivariate/solvers/second_order/newton.jl
- test/multivariate/solvers/second_order/newton_trust_region.jl
Considering that the convergence assessment and the trace update are specific to each solver, I suggest to move those methods from utilities to solver files.
I noticed that a trace method was used for almost all 1st order solver, also a convergence assessment method. So I keep them in utilities with another name and they are called by the `trace!` or `assess_convergence` specific to the solver.
> Move assess_convergence and trace! methods from utilities to solvers

- docs/make.jl
- docs/mkdocs.yml
- docs/src/algo/gradientdescent.md
- docs/src/algo/lbfgs.md
- docs/src/algo/nelder_mead.md
- docs/src/algo/newton.md
- docs/src/algo/newton_trust_region.md
- docs/src/index.md
Math formatting in the docs is [currently broken](http://julianlsolvers.github.io/Optim.jl/v0.9.3/). This PR fixes math formatting by following the [Documenter instructions](https://juliadocs.github.io/Documenter.jl/latest/man/latex/#MkDocs-and-MathJax-1). I also updated all the math to the [recommended syntax for 0.5](https://juliadocs.github.io/Documenter.jl/latest/man/latex/#Julia-0.5-1).
> Fix math formatting in docs

- src/univariate/printing.jl
the `metadata` doesn't have a `"best bound"` entry like the metadata for Brent does
> BUG: Fix printing for GoldenSearch.

- src/multivariate/solvers/first_order/accelerated_gradient_descent.jl
- src/multivariate/solvers/first_order/bfgs.jl
- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
- src/multivariate/solvers/first_order/l_bfgs.jl
- src/multivariate/solvers/first_order/momentum_gradient_descent.jl
- src/multivariate/solvers/second_order/newton.jl
Since new (and existing) users might not always be able to remember how to specify everything, we should have informative doc strings. I've added one for `ConjugateGradient` and one for `BFGS`. The output looks something like
for the former and
for the latter in a 80x43 char sized terminal. Feel free to make PRs against this branch to correct mistakes, suggest additional information and add docstrings for more methods.
> [RFC] Add docstrings to ConjugateGradient, BFGS and the rest

- .travis.yml
- REQUIRE
- src/constraints.jl
- src/interior.jl
- src/problems/constrained.jl
- src/problems/unconstrained.jl
- src/types.jl
Note this is against teh/constrained
> Fix some deprecation warnings

- src/Optim.jl
- src/multivariate/solvers/second_order/krylov_trust_region.jl
- test/multivariate/solvers/second_order/krylov_trust_region.jl
@pkofod  Here's a PR for a trust region method that uses Hessian-vector products. I thought I'd post it now since I'm not sure how you want Optim's types to handle functions that are twice differentiable but only support Hessian-vector products. In the PR, I added a new function type `TwiceDifferentiableHV` but I thought you might be able to suggest a better way.
Also, please let me know what other changes and additions to make to get the PR merged.
Once complete, this PR closes #356.
> WIP: CG/Krylov Trust Region method

- src/multivariate/solvers/second_order/newton.jl
With https://github.com/JuliaNLSolvers/NLSolversBase.jl/commit/cee18b6f975a83c6974118a86b98b037660f2107 this allows for sparse hessians in `Newton()`. `NewtonTrustRegion()` I'm not so sure about currently. There's some type annotation things going on, but I also have to see if the code does something non-sparse-y things.
The solve step should obviously be different. I think we should go ahead and do the call overloading of a LinearSolver type for the `-H\g` calculation as in DiffEq.jl - though there were some issues that they had to work out (is it worked out? cc @ChrisRackauckas).
Just putting this up here. May merge it as it is and not advertise it, or may go all the way in this PR. At the very least we shouldn't be restricting things if there's no reason to.
I wonder if …
> Don't disallow sparse Hessians.

- docs/src/user/config.md
- src/multivariate/optimize/optimize.jl
- src/types.jl
- src/utilities/assess_convergence.jl
- test/general/types.jl
- test/multivariate/complex.jl
- test/multivariate/f_increase.jl
- test/multivariate/manifolds.jl
I want an option for the optimizer to return the final values of `x` and `f(x)`, even if the last iteration results in `f_increased`.  
Let me know whether you think this is a good idea or not. I can also introduce an extra option `pick_increased_f`, instead of piggy-backing on `allow_f_increases`.
> Pick increased f if allow_f_increases is true

- src/types.jl
Currently, we can't use callable types as callback functions. This fixes that issue.
> Allow callable types for callback

- docs/src/algo/lbfgs.md
- src/multivariate/solvers/first_order/l_bfgs.jl
If a preconditioner is not used, I propose that we default to the scaled initial guess for the inverse Hessian as given in Nocedal and Wright. (See 6.21 or 7.20 in the second edition).
I have also included a resetalpha setting for L-BFGS. It should probably be default for all line searches that `alphaguess!` sets `state.alpha=1`. None of the algorithms I know of uses the previous step length as an initial guess anyway. (Maybe for case of Momentum and AcceleratedGradientDescent; but they need a revamp of `alphaguess!` to work properly anyway)
And as the state is now, BackTracking will perform terribly, as it can only decrease step lengths.
> L-BFGS: Use scaled initial guess for inverse Hessian

- src/deprecate.jl
- src/multivariate/optimize/interface.jl
- src/multivariate/optimize/optimize.jl
- src/multivariate/solvers/constrained/fminbox.jl
- src/multivariate/solvers/first_order/accelerated_gradient_descent.jl
- src/multivariate/solvers/first_order/bfgs.jl
- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
- src/multivariate/solvers/first_order/l_bfgs.jl
- src/multivariate/solvers/first_order/momentum_gradient_descent.jl
- src/multivariate/solvers/second_order/krylov_trust_region.jl
- src/multivariate/solvers/second_order/newton.jl
- src/multivariate/solvers/second_order/newton_trust_region.jl
- src/multivariate/solvers/zeroth_order/nelder_mead.jl
- src/multivariate/solvers/zeroth_order/particle_swarm.jl
- src/multivariate/solvers/zeroth_order/simulated_annealing.jl
- src/multivariate/solvers/zeroth_order/zeroth_utils.jl
- src/types.jl
- src/univariate/solvers/brent.jl
- src/univariate/solvers/golden_section.jl
- src/univariate/types.jl
- src/utilities/assess_convergence.jl
- test/runtests.jl
@anriseth @jonathanBieler
Are there other things you found annoying while trying to base your stuff off of Optim? I'll be happy to generalize where needed.
> Use abstract type instead of typealias for solver distinction.

- src/utilities/update.jl
This flushes the standard output every time when a trace is written to it. This is especially useful when we run a long-running optimization and check the convergence from a log file.
> flush trace log

- src/types.jl
This is inspired by the annoying way you have to specify options for bigfloats, see https://discourse.julialang.org/t/optimization-routines-for-bigfloat-doubledouble-higher-precision-objective-and-gradient-functions/8448/3?u=pkofod
> Be less strict in the Options constructor

- REQUIRE
- docs/mkdocs.yml
- docs/src/algo/ngmres.md
- src/Manifolds.jl
- src/Optim.jl
- src/multivariate/optimize/interface.jl
- src/multivariate/optimize/optimize.jl
- src/multivariate/solvers/first_order/ngmres.jl
- test/general/types.jl
- test/multivariate/complex.jl
- test/multivariate/manifolds.jl
- test/multivariate/solvers/first_order/ngmres.jl
- test/runtests.jl
This implements solvers that do two things:
- Show an example of nonlinear preconditioning.
- Introduce two nonlinear preconditioning algorithms that significantly improves the performance of Gradient Descent.
This implements two acceleration algorithms, [Nonlinear GMRES](http://www.hansdesterck.net/Publications-by-topic/nonlinear-preconditioning-for-nonlinear-optimization) and ["Objective Acceleration"](https://arxiv.org/abs/1710.05200).
I have tested them as accelerators on top of Gradient Descent and L-BFGS. For GD it is very efficient, for L-BFGS I am not sure if it has value ( the situations where the accelerators improve L-BFGS, it can be better to combine them with GD instead ).
Give me feedback on 
- whether you think these belong in Optim.jl, or should be a separate package …
> Acceleration / nonlinear preconditioning with N-GMRES and O-ACCEL

- src/multivariate/optimize/optimize.jl
- src/multivariate/solvers/zeroth_order/nelder_mead.jl
- src/utilities/assess_convergence.jl
- test/general/convergence.jl
I've tried to implement some of the changes discussed in #309, which allows my two minimal examples of [ZerothOrderOptimizer](https://gist.github.com/jonathanBieler/47d9ae7e95e7ca0f7352de8f84827ae3) and [FirstOrderOptimizer](https://gist.github.com/jonathanBieler/ed2ae8868e7b317c9e6d2db86f6ed2b9) defined outside of Optim to run.
> RFC: more generic convergence assessment

- REQUIRE
- docs/src/algo/autodiff.md
- docs/src/algo/complex.md
- src/Optim.jl
- src/multivariate/optimize/optimize.jl
- src/objective_types.jl
- test/multivariate/complex.jl
- test/multivariate/fdtime.jl
- test/multivariate/solvers/zeroth_order/particle_swarm.jl
- test/runtests.jl
This tries to use the DiffeqDiffTools finite difference derivatives rather than Calculus.
I made a comparison between the running times using Calculus and this PR, available here:
https://gist.github.com/anriseth/ccc51401525b923fbdc8147b2c8ed36f 
**Summary**: 
- DiffEqDiffTools is much faster at approximating the Hessian if it has access to the gradient
- DiffEqDiffTools is much worse if we approximate the Hessian using the Jacobian of a finite-difference gradient (People should not do this anyway?)
- DiffEqDiffTools is slightly slower at approximating gradients than Calculus. *Could be because the problems tested are too cheap, so the cache allocation is more costly?*
**Preliminary conclusion:**
If this enables FD gradients for complex number optimization, then the little extra cost in …
> DiffeqDiffTools derivatives

- src/multivariate/optimize/interface.jl
- src/multivariate/optimize/optimize.jl
- src/multivariate/solvers/first_order/ngmres.jl
- src/types.jl
- src/utilities/assess_convergence.jl
This PR lets the user set the option `successive_f_tol::Int = n` so that an optimization routine only converges if `f_converged = true` happens `n+1` times in a row. The default is `Options(successive_f_tol=0)`.
This functionality is taken from IPNewton. I like this option, however, as the `f_tol` convergence criteria is a bit artificial. The same goes for `x_tol`, and I can add that as well if you guys wish. Alternatively we can wait with `x_tol` until (if) we rewrite the convergence assesment code.
I also changed the order of the `assess_convergence` functions. As most people care about the unconstrained one, it feels natural to have it first in the file.
> Introduce counter for f_tol (IPNewton support)

- docs/src/algo/samin.md
- src/multivariate/solvers/constrained/samin.jl
- test/multivariate/solvers/constrained/samin.jl
This increases the default temperature reduction rate from 0.5 to 0.9, which is more conservative, and which will be more likely to give the correct solution, at the cost of more iterations. The default tolerances are made more strict. The final results are displayed by default. The documentation has been extended with a bit of advice, and with examples of both successful and unsuccessful runs.
> samin changes: defaults, verbosity, and documentation

- docs/src/algo/autodiff.md
- docs/src/algo/precondition.md
- src/multivariate/optimize/interface.jl
- src/objective_types.jl
```
julia> using Optim, OptimTestProblems
julia> prob = OptimTestProblems.UnconstrainedProblems.examples["Rosenbrock"];
julia> optimize(prob.f, prob.g!,rand(2), Newton(); autodiff=:forward)
Results of Optimization Algorithm
* Algorithm: Newton's Method
* Starting Point: [0.9123284150752757,0.36455247528077095]
* Minimizer: [1.0,1.0]
* Minimum: 0.000000e+00
* Iterations: 7
* Convergence: true
* |x - x'| ≤ 1.0e-32: false 
|x - x'| = 1.33e-09 
* |f(x) - f(x')| ≤ 1.0e-32 |f(x)|: false
|f(x) - f(x')| = Inf |f(x)|
* |g(x)| ≤ 1.0e-08: true 
|g(x)| = 0.00e+00 
* Stopped by an increasing objective: false
* Reached Maximum Number of Iterations: false
* Objective Calls: 17
* Gradient Calls: 17
* Hessian Calls: 7
julia> optimize(prob.f, prob.g!,rand(2), Newton(); autodiff=:finite)
Results of …
```
> Inplace and autodiff keywords and ForwardDiff HessianConfig bug fix

- src/multivariate/solvers/zeroth_order/particle_swarm.jl
This is to avoid division by zero if the swarm has all identical members.
Edit: I should maybe clarify something. We might want to add some sort of convergence checks here, but the underlying idea is that *at all times*  the swarm should be allowed to escape a local minimum. I'm no expert here, but it appears to me that if `d` is so small it will become practically impossible to escape, and then we might just terminate anyway.
> Safe guard division in ParticleSwarm

- REQUIRE
- src/multivariate/solvers/first_order/ngmres.jl
- src/utilities/generic.jl
- src/utilities/perform_linesearch.jl
@anriseth this should sync Optim with LineSearches.
> Update for new line search functionality.

- docs/src/algo/complex.md
- test/multivariate/complex.jl
We should probably find a clever way to add Literate examples to the Examples section of existing docs. Alternatively, we could just list links to them in the `complex.md` file.
Also, @antoine-levitt, do you have any references for me that can be useful to add to the docs?
> Add usage example to complex optimization

- .travis.yml
- docs/generate.jl
- test/REQUIRE
- test/runtests.jl
I forgot to add a file to #632, so the docs generation failed.
This would have been caught if we run the docs generation script from `runtests.jl` in the same way it's done in LineSearches and JuAFEM. @pkofod if you prefer to keep `.travis.yml` as before I can revert the second commit in this PR, otherwise, this is good-to-go.
> Add Literate generator script

- src/multivariate/solvers/constrained/fminbox.jl
I noticed my f_calls_limit option was not respected. Before this change, the below example calls f 1157 times, after the change it calls f 287 times.
```
import Optim
f(x) = (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
x0 = [2.0, 2.0]
lowerbounds = [1.0, 1.0]
upperbounds = [3.0, 3.0]
result = Optim.optimize(
f,
lowerbounds,
upperbounds,
x0,
Optim.Fminbox(Optim.NelderMead()),
Optim.Options(f_calls_limit=100)
)
println(result.f_calls)
```
> pass options arg through to fminbox

- LICENSE.md
- docs/mkdocs.yml
- docs/src/examples/ipnewton_basics.jl
I've fixed the following:
- mkdocs got confused with indented code in my IPNewton example
- Correct link to the maximum likelihood example
- Add `admonition` functionality to MkDocs (to enable `tip` blocks etc.)
@pkofod I have noticed two issues with the `windmill` theme:
- The search page does not work https://github.com/gristlabs/mkdocs-windmill/pull/16
- They don't have any CSS code for the admonition blocks, so they don't stand out as much as in other themese / the HTML format from Documenter.
> Fix example docs and add admonition to mkdocs

- src/Manifolds.jl
- src/multivariate/solvers/constrained/fminbox.jl
- test/multivariate/solvers/constrained/fminbox.jl
Fix #667 
Now that `ind2sub` has been removed, I decided to just call `Base._ind2sub`, but one could also do `CartesianIndices(x)[i].I`. That seemed a bit wasteful, but maybe there is a better way to use the new CartesianIndex systems?
> Use _ind2sub

- REQUIRE
- src/Optim.jl
- test/runtests.jl
I don't think we're using Compat anywhere, so should be remove it? (at least, remove the two `import` lines?)
> Remove Compat?

- src/multivariate/solvers/first_order/cg.jl
- test/multivariate/solvers/first_order/cg.jl
Fix #669 
There's a question as to whether we should restart CG when we hit a NaN-situation instead of the current approach that takes the truncation value `eta_k` instead. I can't find any discussion of this in the CG papers as they conveniently consider nice functions or Wolfe-condition steps.
> Use NaNMath to prevent NaNs in CG

- src/types.jl
- test/runtests.jl
I just tried adding the function in the REPL, so maybe there needs more work, but at least it helps giving a somewhat more readable output. Example:
```julia
julia> myoptions = Optim.Options(x_tol = 1e-10)
x_tol = 1.0e-10
f_tol = 0.0
g_tol = 1.0e-8
outer_x_tol = 0.0
outer_f_tol = 0.0
outer_g_tol = 1.0e-8
f_calls_limit = 0
g_calls_limit = 0
h_calls_limit = 0
allow_f_increases = false
allow_outer_f_increases = false
successive_f_tol = 0
iterations = 1000
outer_iterations = 1000
store_trace = false
show_trace = false
extended_trace = false
show_every = 1
callback = nothing
time_limit = NaN
```
> Implement `show` for Optim.options

- docs/src/algo/nelder_mead.md
Corrected a small typo. 
In Gao & Han (2010, p. 269) they recommend using gamma = 1 - 1/(2n)
Fortunately, the code seems correct in ` Optim.jl/src/multivariate/solvers/zeroth_order/
nelder_mead.jl`, line 28
> Typo in the documentation: Update nelder_mead.md

- docs/src/algo/lbfgs.md
- src/multivariate/solvers/first_order/bfgs.jl
- src/utilities/perform_linesearch.jl
This is mentioned in N&W. They mention that various pieces of software allow a similar choice, but I'm not sure which ones to be honest.
The reason why it can make sense, as far as I understand it, is because extreme search directions (not final steps!) can really mess up the line search. It can be difficult to reach a useful step size in the allowed number of iterations, or a sub-optimal point can be accepted by the inexact line search.
`BFGS(; initial_stepnorm=z)` will scale the initial identity matrix with the supnorm of the gradient times `z`. That number `z` is usually described as the "usual" or "expected" step size. If the initial step size can be guessed and set to `z` it is potentially possible to either a) avoid too many function evaluations in the first iteration and/or b) …
> Initial stepnorm in BFGS

- src/maximize.jl
- src/types.jl
A minimal example of what went wrong:
using Optim
f(x) = x[1]^2
x0 = BigFloat[1]
obj = OnceDifferentiable(f, x0; autodiff = :forward)
result = optimize(obj, x0, BFGS());
println(result)   # This bit crashes.
The final print fails, because (i) the minimizer is an array of length 1, and
(ii) because the solution is stored using BigFloats, it does not fit on a
single line and needs to be abbreviated.
> fix bug in show() when trying to abbreviate singleton arrays

- src/multivariate/precon.jl
To avoid a precompilation error on Julia 1.4.
> Make dot definition on Julia version since it's implemented in Julia 1.4

- src/multivariate/precon.jl
As discussed in https://github.com/JuliaNLSolvers/Optim.jl/pull/749#issuecomment-533347789, I added a `if` block so that `dot(::Array, ::Diagonal, ::Array)` defined in LinearAlgebra would be used in Julia 1.4.
The corresponding function is defined in https://github.com/JuliaLang/julia/commit/2425ae760fb5151c5c7dd0554e87c5fc9e24de73#diff-931712efb02f1f24866de113b19d54a3R645-R647 which gives the version number:
```console
$ contrib/commit-name.sh 2425ae760fb5151c5c7dd0554e87c5fc9e24de73
1.4.0-DEV.92
```
> Use LinearAlgebra.dot(::Array, ::Diagonal, ::Array) in Julia 1.4

- test/multivariate/f_increase.jl
- test/runtests.jl
While writing #755, I noticed that not all `multivariate/*.jl` were included in the test.  There are now 10 files there:
```console
$ ls -lh1 multivariate/*.jl | wc -l
10
```
Adding `"f_increase"` would match the number:
```console
$ grep --line-number -A11 '## other' runtests.jl
84:    ## other
85-    "array",
86-    "extrapolate",
87-    "lsthrow",
88-    "precon",
89-    "manifolds",
90-    "complex",
91-    "fdtime",
92-    "arbitrary_precision",
93-    "successive_f_tol",
94-    "f_increase",
95-]
```
I also tweaked the test to make it pass.
> Include test/multivariate/f_increase.jl

- src/Optim.jl
- src/multivariate/solvers/second_order/newton_trust_region.jl
- test/multivariate/solvers/first_order/ngmres.jl
Use the safeguards from Moré and Sorensen. I have this in "new optim", but thought I'd port it over. It's useful in several cases.
In the positive definite case, the un-safeguarded lambda will subtract a multiple of I from H. This is crazy since a newton step based on PD H is good, it just turned out to be outside of the trust region. If we then subtract something we'll move *further* away from the trust region boundary instead of cloesr to it!. It also tends to make the H_ridged almost singular (although not quite) - just think about the diagonal case, where this will replace an entry with something like `1e-8`! 
Beyond that, there's a chance that for very large eigenvalues, `1e-8` is below the granularity of the floating point numbers, and this can cause an actual eigenvalue to become …
> Tr safeguards

- docs/src/algo/newton_trust_region.md
- docs/src/algo/ngmres.md
- docs/src/algo/samin.md
- docs/src/user/tipsandtricks.md
All examples with UnconstrainedProblems now correctly refer to
the package OptimTestProblems.
> Fixes for OptimTestProblems.UnconstrainedProblems

- docs/src/algo/manifolds.md
- src/Manifolds.jl
- test/multivariate/array.jl
The option `Manifold=sphere()` is supposed to handle multidimensional arrays.  This adds a failing test as a reminder that it doesn't yet.
> Normalized multidimensional arrays

- src/multivariate/solvers/second_order/krylov_trust_region.jl
Otherwise using Float32s fails without setting the initial radius
> Convert initial radius to match types

- src/multivariate/solvers/constrained/samin.jl
This is a trivial fix about error printing (currently prints `%d` instead of the coordinate index).
> fix printf syntax in error message

- src/multivariate/solvers/constrained/ipnewton/ipnewton.jl
Allows custom array types that have the ```similar``` method implemented to be passed through the ```IPNewton``` solver. For example [labeled arrays](https://github.com/JuliaDiffEq/LabelledArrays.jl).
> Change initial_state in ipnewton.jl to allow broader class of AbstractArrays

- docs/make.jl
- docs/src/examples/ipnewton_basics.jl
- src/multivariate/optimize/interface.jl
- src/multivariate/solvers/constrained/ipnewton/ipnewton.jl
- test/multivariate/solvers/constrained/ipnewton/constraints.jl
This just adds a couple of convenience methods. CC @ChantalJuntao.
I also found I needed to add `sitename` to get the docs to build. Not sure if you want that or not, but I thought I'd offer. Happy to strip that commit from the PR if necessary.
> Support creation of `TwiceDifferentiable` from `IPNewton` methods

- src/multivariate/solvers/first_order/bfgs.jl
- test/multivariate/solvers/constrained/fminbox.jl
I know about damped BFGS, and resetting, and so on and so forth. It just so happened that I ran into a case where invH wound up indefinite after the update, so I'm fine with using the skipping strategy here. It's especially relevant when using backtracking because the updates are not guaranteed to be well PD, but the steps might still be perfectly fine.
> Skip updates if dx_dg is non-positive in BFGS

- joss/Makefile
- src/api.jl
Fixes the following two (unrelated) bugs:
1. simplex_trace and centroid_trace functions are missing call to trace method
2. pandoc has replaced --latex-engine flag with --pdf-engine
> Fix minor bugs

- Project.toml
FillArrays has been updated to 0.9 with new features but no breaking changes.
With julia 1.5 out there may be other updates too but this is the one I need right now...
> Bump FillArrays version

- src/Manifolds.jl
- test/multivariate/manifolds.jl
Fixes #752
Don't merge yet!
To test the change, I simply repeated the test done for `Stiefel_SVD`. However, the test fails then with
```
Stiefel, retraction = CholQR: Error During Test at /Users/jagot/.julia/dev/Optim/test/multivariate/manifolds.jl:14
Got exception outside of a @test
ArgumentError: Search direction is not a direction of descent.
Stacktrace:
[1] (::LineSearches.HagerZhang{Float64,Base.RefValue{Bool}})(::Function, ::getfield(LineSearches, Symbol("#ϕdϕ#6")){Optim.ManifoldObjective{OnceDifferentiable{Float64,Array{Complex{Float64},2},Array{Complex{Float64},2}}},Array{Complex{Float64},2},Array{Complex{Float64},2},Array{Complex{Float64},2}}, ::Float64, ::Float64, ::Float64) at /Users/jagot/.julia/packages/LineSearches/WrsMD/src/hagerzhang.jl:120
[2] HagerZhang at …
```
> WIP: Corrected Stiefel_CholQR

- src/multivariate/optimize/optimize.jl
- src/multivariate/solvers/constrained/fminbox.jl
- src/multivariate/solvers/first_order/bfgs.jl
- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
- src/multivariate/solvers/first_order/l_bfgs.jl
- src/types.jl
- test/multivariate/arbitrary_precision.jl
> Don't re-create the cache in every iteration of Fminbox as it calls the objective too often

- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
- src/multivariate/solvers/first_order/l_bfgs.jl
- src/univariate/optimize/interface.jl
- src/univariate/solvers/brent.jl
- src/univariate/solvers/golden_section.jl
- test/univariate/optimize/interface.jl
Fixes #853 
Some methods still have Function annotations left over form waay back where `Function` covered most the things that were "callable".
> Don't use Function signatures.

- docs/src/user/minimization.md
- src/multivariate/solvers/constrained/ipnewton/interior.jl
- test/multivariate/solvers/constrained/ipnewton/interface.jl
As an alternative to Fminbox when you have second order information.
> Make it easier to use IPNewton if you only have bounds.

- src/multivariate/solvers/constrained/fminbox.jl
- test/multivariate/solvers/constrained/fminbox.jl
Only evaluate the barrier term (to terminate linesearches etc) if out of box. #861
> Fix out-of-box in Fminbox.

- .github/workflows/linux.yml
- .github/workflows/linux_nightly.yml
- .github/workflows/mac.yml
- .github/workflows/mac_nightly.yml
- .github/workflows/windows.yml
- .github/workflows/windows_nightly.yml
Adds CI for Linux, Windows, and OSX via GitHub actions (timely considering the Travis recent move to credits). There are 6 files (two per OS, for the current stable versions `v1` and the `nightly` version).
Note you will need to add you CODECOV token to the secrets for the coverage during these runs to be accounted for.
> Add Github Action CI

- src/multivariate/solvers/constrained/ipnewton/utilities/trace.jl
- src/multivariate/solvers/second_order/newton_trust_region.jl
- src/multivariate/solvers/zeroth_order/nelder_mead.jl
- src/types.jl
- src/univariate/printing.jl
- test/multivariate/array.jl
Some type parameterizations are ambiguous on v1.6, a test fails on v1.6, and nan's and infs in eigen now throws.
> Fix some v1.6 stuff

- src/multivariate/solvers/second_order/newton.jl
Negating the search direction instead of the whole hessian saves some 
computation and allocations.
> Change order of ldiv and - in sparse Newton.

- src/multivariate/solvers/zeroth_order/nelder_mead.jl
> Fix eachindexing and dots for NelderMead.

- Project.toml
- src/multivariate/optimize/optimize.jl
- src/types.jl
- test/multivariate/measurements.jl
- test/runtests.jl
paves the way to use Optim with Measurements. calculations runs and seems to propagate the uncertainty. fixes #823 . fixing the show problem could be done in two ways:
- trying to use other way of formatting numbers, compatible with `Measurements`.
- displaying only the value. this can be done on a two liner:
```
using Printf,Measurements
Printf.tofloat(x::Measurement) = Printf.tofloat(Measurements.value(x))
```
if the user doesnt want to do this, they can directly use Optim.minimizer(res) or Optim.minimum(res) and not show the summary of the optimization procedure.
as this type relaxation doesnt seem to affect other number types, this is an strict improvement over the current situation.
> relax type constraints to support Measurements

- Project.toml
- src/Optim.jl
- src/multivariate/solvers/first_order/bfgs.jl
TODO:
MWE:
```
using Optim, CUDA
rosenbrock(x) =  (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
result = optimize(rosenbrock, cu(zeros(2)), BFGS())
```
Prev:
```
ERROR: ArgumentError: cannot take the CPU address of a CuArray{Float32, 1}
Stacktrace:
[1] unsafe_convert(#unused#::Type{Ptr{Float32}}, x::CuArray{Float32, 1})
@ CUDA ~/.julia/packages/CUDA/mVgLI/src/array.jl:262
[2] gemv!(trans::Char, alpha::Float32, A::Matrix{Float32}, X::CuArray{Float32, 1}, beta::Float32, Y::CuArray{Float32, 1})
@ LinearAlgebra.BLAS /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/blas.jl:704
[3] gemv!(y::CuArray{Float32, 1}, tA::Char, A::Matrix{Float32}, x::CuArray{Float32, 1}, α::Bool, β::Bool)
@ LinearAlgebra /buildworker/worker/package_linux64/build/usr/share/julia/stdli …
```
> BFGS GPU Support

- docs/mkdocs.yml
Edit links point to
https://github.com/JuliaNLSolvers/Optim.jl/edit/master/docs/
and not to
https://github.com/JuliaNLSolvers/Optim.jl/edit/master/docs/src/
> Fix edit link at bottom of each page

- Project.toml
- docs/src/examples/maxlikenlm.jl
The ML example in the documentation (https://julianlsolvers.github.io/Optim.jl/stable/#examples/generated/maxlikenlm/) has some problems. The t-statistics are not correct, as can be verified by computing the OLS estimates. The error is that the transformation from log sigma to sigma is not correctly done. The Hessian matrix is computed after directly exponentiating the log sigma parameter, while the likelihood function is not prepared to accept sigma rather than log sigma, so the resulting Hessian is not correct. This PR uses the delta method to do the transformation.
> fix for ML example

- docs/src/user/tipsandtricks.md
- src/multivariate/optimize/interface.jl
- src/multivariate/optimize/optimize.jl
- src/multivariate/solvers/constrained/ipnewton/interior.jl
- src/multivariate/solvers/constrained/samin.jl
- src/multivariate/solvers/first_order/bfgs.jl
- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
- src/types.jl
- src/univariate/solvers/brent.jl
- src/univariate/solvers/golden_section.jl
- src/utilities/perform_linesearch.jl
- src/utilities/update.jl
- test/multivariate/optimize/interface.jl
- test/multivariate/optimize/optimize.jl
As pointed out in https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/pull/240#discussion_r744598754 - I couldn't find good documentation in base julia beyond a bullet point in https://docs.julialang.org/en/v1/manual/noteworthy-differences/, but there's also https://stackoverflow.com/questions/56852880/comparing-julia-variable-to-nothing-using-or ...
Optim also requires Julia >= 1.2, so if you prefer we could change the checks to `isnothing`/`!isnothing`?
> check for nothing with ===/!== instead of ==/!=

- src/types.jl
- test/general/types.jl
- test/runtests.jl
Re-implement two-argument Base.show() such that it produces an executable string of Optim.Options() as specified in Base docs [1].
Move previous implementation to three-argument Base.show() which should be human-readable [2].
[1] https://docs.julialang.org/en/v1/base/io-network/#Base.show-Tuple{IO,%20Any}
[2] https://docs.julialang.org/en/v1/base/io-network/#Base.show-Tuple{IO,%20Any,%20Any}
Refs: #915
>  fix(show)!: produce executable string for Options

- src/multivariate/solvers/second_order/newton_trust_region.jl
This bug was caught by @NittanyLion in #963 . Thanks!
> Fix delta update if rho < eta in newton trust region

- README.md
I noticed the build badges are currently pointing at old builds on both Travis CI (from a year ago) and Appveyor (original repository by @blegat 5 years ago).
I corrected the image and links, now pointing towards the Github CI actions (Linux, macOS, Windows).
> Fix incorrect URL for build badges

- src/univariate/printing.jl
Unbound type parameters often cause performance issues and run time dispatch.
Issue found using https://github.com/JuliaLang/julia/pull/46608
> remove unbound type parameter

- src/multivariate/optimize/interface.jl
- src/multivariate/solvers/constrained/ipnewton/ipnewton.jl
- src/multivariate/solvers/first_order/accelerated_gradient_descent.jl
- src/multivariate/solvers/first_order/momentum_gradient_descent.jl
- src/multivariate/solvers/first_order/ngmres.jl
- test/multivariate/solvers/first_order/ngmres.jl
- test/runtests.jl
> Use namedtuple for default options.

- src/multivariate/solvers/zeroth_order/particle_swarm.jl
> Rework lower/upper in ParticleSwarm for stability.

- src/multivariate/optimize/interface.jl
- test/multivariate/optimize/interface.jl
> Fix bug in add default options

- src/utilities/perform_linesearch.jl
When training with GPU, sometimes the following error will occur, causing function `optimize` failure.
```julia
ERROR: GPU compilation of kernel #broadcast_kernel#28(CUDA.CuKernelContext, CuDeviceMatrix{Float64, 1}, Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(identity), Tuple{Base.Broadcast.Extruded{Matrix{Float64}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}}}, Int64) failed
KernelError: passing and using non-bitstype argument
Argument 4 to your kernel function is of type Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(identity), Tuple{Base.Broadcast.Extruded{Matrix{Float64}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}}}, which is not isbits:
.args is of type …
```
> fix `reset_search_direction!` failure when training with GPU

- src/multivariate/optimize/optimize.jl
This PR checks that the gradient and Hessian are all finite, otherwise it breaks early with a warning.
> exit early when nan in grad or hessian

- src/utilities/maxdiff.jl
The maxdiff function used in assess_convergence allocates which causes a non negligible time increase in a large-ish LBFGS problem for me.
#889 switched maxdiff to a mapreduce based implementation to support gpu arrays.
Unfortunately the mapreduce now allocates for standard arrays.
This change restores the previous allocation free code for normal Arrays while still allowing gpu arrays using mapreduce
> restore allocation free maxdiff

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
JuMP v1.15 now supports providing the nonlinear objective and constraints with `@objective` and `@constraint`.
The old syntax `@NLobjective` and `@NLconstraint` is kept for backward compatibility only.
Since the MOI wrapper in Optim is new, we don't need to support the old interface so this PR replace it the new one which works with `@objective` and `@constraint`.
> Update to new MOI nonlinear interface

- src/Optim.jl
- src/multivariate/solvers/first_order/adam.jl
- src/multivariate/solvers/first_order/adamax.jl
- test/multivariate/solvers/first_order/adam_adamax.jl
- test/runtests.jl
Fixes #1012 
I don't use Adam and AdaMax myself, but I suppose the slow convergence of Adam from `zeros(2)` is sort of expected sometimes? Otherwise it may be good to compare against another implementation.
```
julia> rosenbrock(x) =  (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
rosenbrock (generic function with 1 method)
julia> result = optimize(rosenbrock, ones(2), AdaMax(), Optim.Options(iterations=5000))
* Status: success
* Candidate solution
Final objective value:     5.647600e-17
* Found with
Algorithm:     AdaMax
* Convergence measures
|x - x'|               = 1.50e-08 ≰ 0.0e+00
|x - x'|/|x'|          = 1.50e-08 ≰ 0.0e+00
|f(x) - f(x')|         = NaN ≰ 0.0e+00
|f(x) - f(x')|/|f(x')| = NaN ≰ 0.0e+00
|g(x)|                 = 9.95e-09 ≤ 1.0e-08
* Work counters
Seconds run:   0  (vs …
```
> Add Adam and AdaMax

- README.md
x-ref https://github.com/jump-dev/JuMP.jl/pull/3624
I've made quite a few changes, so it's probably best viewed https://github.com/odow/Optim.jl/blob/patch-1/README.md
Main changes are:
* Remove table of badges
* Use explicit Markdown links
* Remove mathematical description of rosebbrock
* Remove suggestion to tag `@pfkod` explicitly
* Fix JuMP example, which @blegat got wrong 😆 (missing objective sense)
> Update and reorganize README.md

- src/multivariate/solvers/first_order/adam.jl
- src/multivariate/solvers/first_order/adamax.jl
- test/multivariate/solvers/first_order/adam_adamax.jl
This is a small PR for Adam and AdaMax methods (thanks a lot for adding them to `Optim.jl`) to 
- fix issue https://github.com/JuliaNLSolvers/Optim.jl/issues/1096 (when using `extended_trace=true`) by adding `alpha` to the respective `State` structs, so that `common_trace!` works out of the box.
- generalise `alpha` (and effected `update_state!`) for both `Adam` and `AdaMax` such that they can accept a callable object - a function or in particular a scheduler. This helps in using the functionality from [ParameterSchedulers.jl](https://github.com/FluxML/ParameterSchedulers.jl) seamlessly, without adding it as a dependency.
> Fixing extended trace failure for Adam and AdaMax and generalising `alpha` parameter to accept callable object (scheduler)

- docs/src/user/config.md
Looking at the [source code](https://github.com/JuliaNLSolvers/Optim.jl/blob/b041bd63373cf2403180c6993eff235b5c010670/src/types.jl#L97) the default value for `allow_f_increases`  seems to be `true` and not `false` as indicated in the docs. Same for `allow_outer_f_increases`.
Looks like it was missed to update in #847.
> Fix default of `allow_f_increases` and `allow_outer_f_increases` in docs

- ext/OptimMOIExt.jl
- test/MOI_wrapper.jl
As highlighted in https://github.com/JuliaNLSolvers/Optim.jl/issues/1071, most tests were failing because the starting point was infeasible.
With this PR, most are now passing.
The remaining ones to investigate are:
* `test_nonlinear_expression_hs071` : this one gives an infeasible solution, not sure if it's due to the fact that the starting values does not satisfy the constraints, no warning is thrown though.
* `test_nonlinear_expression_hs071_epigraph` : the variables are in the interior of the bounds but some of the constraints are not satisfied hence the warning is thrown. Then it converges to an incorrect solution
* `test_objective_FEASIBILITY_SENSE_clears_objective` : this one seems it may be a bug in the MOI wrapper, let me investigate first
> Start in interior of variable bounds

- docs/Project.toml
- docs/make.jl
- docs/src/algo/adam_adamax.md
- docs/src/algo/cg.md
- docs/src/algo/complex.md
- docs/src/algo/lbfgs.md
- docs/src/algo/manifolds.md
- docs/src/algo/nelder_mead.md
- docs/src/algo/newton_trust_region.md
- docs/src/algo/ngmres.md
- docs/src/algo/particle_swarm.md
- docs/src/algo/samin.md
- docs/src/refs.bib
Currently the references are enumerated at the end of doc pages, but as more references are added (as seen by empty headers on some other doc pages), it'll be useful to have a citation management tool with Documenter.jl.
> Use DocumenterCitations.jl

- .github/workflows/benchmark_pr.yml
- benchmark/Project.toml
- benchmark/benchmarks.jl
This creates a simple benchmark for catching performance regressions on small, tightly controlled problems. To kick things off I added the multivariate first-order optimizers including `Adam`, `AdaMax`, `BFGS`, `LBFGS`, `NGMRES`, `ConjugateGradient`, `GradientDescent`, and `MomentumGradientDescent`.
The specific benchmark I added is fitting the Gabor function (2 parameters) to a noisy dataset.
It's compatible with any library supporting BenchmarkTools.jl. You can run the benchmark with:
```julia
using Optim
using Pkg
Pkg.activate("benchmark")
include("benchmark/benchmarks.jl")
results = run(SUITE)
@show results
```
I also add a GitHub action to run AirspeedVelocity.jl on this benchmark for any new PR. It will automatically print out the performance and load time comparison of master in a …
> Create benchmark suite

- src/multivariate/solvers/constrained/ipnewton/ipnewton.jl
As per #976, it looks like in this code in `IPNewton`:
https://github.com/JuliaNLSolvers/Optim.jl/blob/adc5b277b3f915c25233b45f8f2dd61006815e63/src/multivariate/solvers/constrained/ipnewton/ipnewton.jl#L282-L288
...the line `state.ev == equality_violation(constraints, state)` probably meant assignment, not an equality test:
1. The equality test would make sense if it was the last statement of the function (in order to return `true` or `false`), but it's not, which means that the result of comparison is not used.
2. As I understand it, `state.ev` is supposed to be a number, most likely a floating-point, but comparison of floats for _equality_ [can fail](https://floating-point-gui.de/errors/comparison/), because of rounding errors, so this equality test seems suspicious.
I changed it to …
> fix: equality comparison where assignment was likely meant

- docs/src/algo/lbfgs.md
This is an approach to #1163
Since even after very many tries I did not get beyond a few cross reference errors on the examples – they do render but something seems still wrong, I will try this PR to maybe render and look at the docs.
> Improve (L-)BFGS docs

- src/multivariate/solvers/first_order/cg.jl
After the formatting of the repository in #1150 , a small error was introduced in the `update_state!` function in the `src/multivariate/solvers/first_order/cg.jl` file: the preconditioner is not updated at every iteration, but only at the first one. The change ensures that the `_apply_precondprep` method is called. Changes:
* [`src/multivariate/solvers/first_order/cg.jl`](diffhunk://#diff-0a73ae73cf3162a4ba402251714e7921cc7521eae370fae3ff1539b469bcd1d1R187): Added a call to `_apply_precondprep(method, state.x)`
> BUGFIX: Update preconditioner in cg

- Project.toml
- src/types.jl
- test/general/types.jl
This implements the feature described in #1171. I did not add the deprecated keyword arguments that are possible to pass to the `Optim(; kws..)` constructor; since this would be new API, it seemed unnecessary.
~~The implementation is not very DRY, since it needs to repeat the valid keyword arguments - but cleaner solutions would probably require a dependency like SetFields.jl or Accessors.jl, which doesn't feel warranted for a small feature like this.~~
> add `Options(options; kws...)` for inheriting from an existing options set
