- src/Optim.jl
- src/accelerated_gradient_descent.jl
- src/bfgs.jl
- src/cg.jl
- src/gradient_descent.jl
- src/l_bfgs.jl
- src/linesearch/backtracking_linesearch.jl
- src/linesearch/hz_linesearch.jl
- src/linesearch/interpolating_linesearch.jl
- src/linesearch/mt_linesearch.jl
- src/momentum_gradient_descent.jl
- src/newton.jl
- src/utils.jl
> Don't add special behavior to Base.dot

- REQUIRE
I don't think we can claim to support 0.2 and prereleases at this point.
> bump minimum julia version requirement

- src/Optim.jl
> Allow precompilation

- src/types.jl
- test/runtests.jl
- test/types.jl
tl;dr: This makes printing not suck when you have a large parameter space.
> Print something readable for problems with more than two parameters

- src/l_bfgs.jl
This gives a basic demonstration of how we could fix the L-BFGS code to resolve the situation shown in #143 .
```jl
julia> using Optim
INFO: Recompiling stale cache file /Users/johnmyleswhite/.julia/lib/v0.4/Optim.ji for module Optim.
julia> function rosenbrock(x::Vector)
return (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
end
rosenbrock (generic function with 1 method)
julia> function rosenbrock_gradient!(x::Vector, storage::Vector)
storage[1] = -2.0 * (1.0 - x[1]) - 400.0 * (x[2] - x[1]^2) * x[1]
storage[2] = 200.0 * (x[2] - x[1]^2)
end
rosenbrock_gradient! (generic function with 1 method)
julia> fr = rosenbrock
rosenbrock (generic function with 1 method)
julia> gr! = rosenbrock_gradient!
rosenbrock_gradient! (generic function with 1 method)
julia> …
```
> [WIP]: Reset search direction in L-BFGS code to ensure descent

- src/l_bfgs.jl
I think this is what was intended.
> fix ftol convergence criterion in l_bfgs_b

- src/newton.jl
- test/newton.jl
> Fix recursion issue when calling Newton without hessian

- README.md
- src/Optim.jl
- src/api.jl
- src/brent.jl
- src/golden_section.jl
- src/types.jl
- test/api.jl
- test/array.jl
- test/bfgs.jl
- test/brent.jl
- test/cg.jl
- test/constrained.jl
- test/golden_section.jl
- test/gradient_descent.jl
- test/l_bfgs.jl
- test/levenberg_marquardt.jl
- test/nelder_mead.jl
- test/newton.jl
- test/optimize.jl
- test/runtests.jl
- test/simulated_annealing.jl
- test/types.jl
So I figured that these changes / additions were way over due, and starting a PR would be a good motivational factor.
Most of it is based of off @johnmyleswhite 's branch.
- Renamed `it` to `iterations`
- Added `iteration_converged` to UnivariateOptimizationResults
- Added API methods for accessing fields of OptimizationResults
I have a small though, and you may not agree with it. Is there a reason why we define the "exceeded iterations" convergence criterion opposite of the others, such that "false" is good and "true" is bad? 
Please add comments or ideas about improvements to the API. 
Fixes #76 
**Update**
Since #149 was merged, it's probably worth it to continue with this. Please comment and discuss.
> Getting the API train running

- README.md
Adding @cortner s test example from #190
> Add documentation for preconditioning.

- src/types.jl
- test/api.jl
Making sure that the fields are actually there, as required.
>  Small test for content of extended trace in BFGS and NelderMead.

- src/problems/unconstrained.jl
> fix hessian calculation

- src/cg.jl
That should do it, right @cortner ?
> Fix bug in direction reset in cg.jl.

- README.md
Make d4 explicit + show optimizer option
> Improve Readme for Box minimization

- docs/src/index.md
I as a user would like to know first what is it, then install the package. :)
> Placing the HOW section after WHAT and WHY.

- README.md
- docs/src/user/tipsandtricks.md
- src/levenberg_marquardt.jl
- src/particle_swarm.jl
- test/constrained.jl
- test/particle_swarm.jl
- test/precon.jl
> Make use of lower, upper, and inital_x consistent.

- src/accelerated_gradient_descent.jl
- src/bfgs.jl
- src/cg.jl
- src/gradient_descent.jl
- src/l_bfgs.jl
- src/momentum_gradient_descent.jl
- src/newton.jl
- src/newton_trust_region.jl
- test/initial_convergence.jl
- test/runtests.jl
> Assess g_convergence before applying algorithm

- README.md
Stemming from [this discussion](https://groups.google.com/forum/#!topic/julia-users/Nwt8bEwe7xU) on julia-users mailing list.
> More links to docs in README

- NEWS.md
- docs/src/user/minimization.md
- src/particle_swarm.jl
I thought we might as well ship some of the post v0.6.0 commits already as a patch. I don't intend to ANN patches, but these will be included in the ANN for v0.7. 
I added a note about the convergence check added in #262 which should close #261 for now.
> Prepare for v0.6.1.

- src/levenberg_marquardt.jl
- test/levenberg_marquardt.jl
> stay within bounds

- src/levenberg_marquardt.jl
Currently, LevenbergMarquardt calls old API
> Fix depwarn

- test/type_stability.jl
> Remove NewtonTrustRegion from type stability tests.

- NEWS.md
- benchmarks/adfd.jl
- benchmarks/timing.jl
- src/api.jl
- src/brent.jl
- src/deprecate.jl
- src/fminbox.jl
- src/golden_section.jl
- src/types.jl
- test/bfgs.jl
- test/constrained.jl
- test/gradient_descent.jl
- test/initial_convergence.jl
- test/l_bfgs.jl
- test/momentum_gradient_descent.jl
- test/nelder_mead.jl
- test/newton.jl
- test/newton_trust_region.jl
> minimum -> minimizer and f_minimum -> minimum.

- NEWS.md
- src/optimize.jl
- test/optimize.jl
> Add `optimize` call to catch all the cases

- REQUIRE
- src/optimize.jl
This is needed for https://github.com/jeff-regier/Celeste.jl/pull/445.
> Bump ForwardDiff to 0.3.x

- NEWS.md
minor bump, as we made the minimizer/minimum final... closes #310  when tagged
I'll let the tests run for good measure, and then I'll tag
> Prepare for v0.7.0.

- src/utilities/assess_convergence.jl
I tried to make a unit test, but my attempts to construct functions that reliably forced different types of convergence were getting a little clunky, so I thought I'd just submit the fix.  If you really want tests, LMK and we can talk about how best to do it.
> Fix f convergence

- src/bfgs.jl
The `I` was used to reset `invH`, but it is more appropriate to follow the `initial_invH` that the user specifies, and then `state.I` is superfluous.
> Fix use of initial_invH in BFGS.

- docs/src/algo/simulated_annealing.md
- src/deprecate.jl
- src/simulated_annealing.jl
taken from  #337 as it's sorta orthogonal to the main change in that pr
> Fix neighbor keyword in simulated annealing.

- test/Optim.jl
> Test for ambiguities.

- docs/src/algo/autodiff.md
- docs/src/algo/precondition.md
- docs/src/dev/contributing.md
- docs/src/user/minimization.md
Just some doc changes from #337 that are unrelated to the work there.
> Docs changes

- src/Optim.jl
- src/accelerated_gradient_descent.jl
- src/bfgs.jl
- src/cg.jl
- src/gradient_descent.jl
- src/l_bfgs.jl
- src/momentum_gradient_descent.jl
- src/newton.jl
- src/newton_trust_region.jl
- src/utilities/perform_linesearch.jl
> Refactor linesearch.

- src/brent.jl
- src/golden_section.jl
- test/brent.jl
- test/golden_section.jl
In this case, the iteration finished immediately. Also added tests,
and further tests for getting errors with x_upper < x_lower.
> Allowed x_upper == x_lower for univariate methods.

- src/accelerated_gradient_descent.jl
- test/accelerated_gradient_descent.jl
- test/bfgs.jl
- test/cg.jl
- test/extrapolate.jl
- test/gradient_descent.jl
- test/l_bfgs.jl
- test/momentum_gradient_descent.jl
- test/nelder_mead.jl
- test/newton.jl
- test/optimize.jl
- test/precon.jl
- test/type_stability.jl
The idea is to remove a lot of the direct use of `*Differentiable` as we are moving towards discouraging this format for most users.
> Simplify some tests.

- README.md
Seems like our algorithms have improved :+1:
> Update README output

- docs/src/user/tipsandtricks.md
> Add at-timeit example to tips-and-tricks.

- .travis.yml
- appveyor.yml
- src/accelerated_gradient_descent.jl
- src/autodiff.jl
- src/bfgs.jl
- src/brent.jl
- src/cg.jl
- src/constraints.jl
- src/fminbox.jl
- src/golden_section.jl
- src/gradient_descent.jl
- src/interior.jl
- src/l_bfgs.jl
- src/momentum_gradient_descent.jl
- src/nelder_mead.jl
- src/newton.jl
- src/simulated_annealing.jl
- src/types.jl
- test/constrained.jl
This is against teh/constrained, not master.
> Updates for Julia 0.6

- appveyor.yml
This PR is against `teh/constrained`
xref: https://github.com/JuliaNLSolvers/Optim.jl/pull/412#discussion_r117617185
> update appveyor settings

- NEWS.md
- src/multivariate/solvers/constrained/fminbox.jl
- test/multivariate/solvers/constrained/constrained.jl
I prefer to warn the user and move their initial guess inside the box, rather than error and exit.
The updated values are rather arbitrary.
> Move initial condition inside box

- docs/src/algo/conjugategradient.md
- docs/src/algo/gradientdescent.md
- docs/src/algo/lbfgs.md
- docs/src/algo/linesearch.md
- docs/src/algo/newton.md
- docs/src/dev/contributing.md
- src/multivariate/solvers/constrained/fminbox.jl
- src/multivariate/solvers/first_order/accelerated_gradient_descent.jl
- src/multivariate/solvers/first_order/bfgs.jl
- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
- src/multivariate/solvers/first_order/l_bfgs.jl
- src/multivariate/solvers/first_order/momentum_gradient_descent.jl
- src/multivariate/solvers/second_order/newton.jl
- test/multivariate/lsthrow.jl
this PR is the `Optim.jl` counterpart to [PR #43 in LineSearches](https://github.com/JuliaNLSolvers/LineSearches.jl/pull/43)
> switched all line search functions to line search types

- REQUIRE
- src/utilities/perform_linesearch.jl
- test/general/counter.jl
- test/multivariate/lsthrow.jl
- test/runtests.jl
> Add tests for f,g,h counters

- .travis.yml
- NEWS.md
- REQUIRE
- appveyor.yml
- docs/src/algo/autodiff.md
- src/Optim.jl
- src/objective_types.jl
- test/general/objective_types.jl
Sorry @anriseth but we have to wait for ReverseDiff to get up to speed wrt ForwardDiff :)
> Move to v0.6 and drop ReverseDiff for now

- src/multivariate/solvers/zeroth_order/particle_swarm.jl
- test/multivariate/solvers/zeroth_order/particle_swarm.jl
> Fix empty constructor for ParticleSwarm

- src/multivariate/optimize/interface.jl
- src/objective_types.jl
- test/multivariate/extrapolate.jl
- test/multivariate/optimize/interface.jl
It will probably help a few people migrate. We might remove it at some point, but I don't think it hurts to have it.
> Add UninitializedObjective functionality.

- src/univariate/types.jl
- test/runtests.jl
- test/univariate/dual.jl
> Allow dualnumbers in univariate optimisation

- src/multivariate/solvers/first_order/accelerated_gradient_descent.jl
- src/multivariate/solvers/first_order/bfgs.jl
- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
- src/multivariate/solvers/first_order/l_bfgs.jl
- src/multivariate/solvers/first_order/momentum_gradient_descent.jl
- src/multivariate/solvers/second_order/newton.jl
These commented out codes seem superfluous?
> Remove #uncomment for v0.8.0 stuff

- src/univariate/solvers/brent.jl
- src/univariate/solvers/golden_section.jl
Not much to show, as there <s>are</s>is currently nothing to set using the constructors.
> Add docstrings to univariate special casese

- README.md
There might be some people out there who are not familiar with the Rosenbrock function but are interested in this package ;)
> Short explanation of the Rosenbrock function.

- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
> Use dot notation

- src/multivariate/optimize/interface.jl
- src/multivariate/optimize/optimize.jl
- src/multivariate/solvers/second_order/krylov_trust_region.jl
- test/general/counter.jl
- test/multivariate/solvers/second_order/krylov_trust_region.jl
- test/runtests.jl
The tests for `KrylovTrustRegion` were not enabled in #416. I have enabled them, and fixed all the resulting errors.
> Enable KrylovTrustRegion tests, and fix for new API

- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
- src/multivariate/solvers/second_order/krylov_trust_region.jl
- src/multivariate/solvers/second_order/newton.jl
Thanks to https://github.com/JuliaNLSolvers/Optim.jl/pull/475#issuecomment-338956044
Will cause a merge conflict for #474 (I hope?)
> Add more dots

- docs/src/algo/precondition.md
This example probably relied on an earlier version of ForwardDiff.
> Fix preconditioning example

- docs/src/user/minimization.md
- src/multivariate/optimize/optimize.jl
Some users seem a bit confused that you cannot use gradient descent or newton's method for univariate optimization, and of course you can. This hopefully helps a bit.
> Better univarate docs to avoid confusion

- src/multivariate/optimize/interface.jl
- test/multivariate/optimize/interface.jl
> Fix overwriting of initial guess

- src/utilities/assess_convergence.jl
- src/utilities/perform_linesearch.jl
In my previous commit on this convergence assessment, I forgot to update this line.
> Soft bounds on x_abschange

- src/multivariate/optimize/optimize.jl
- src/types.jl
> Fix complex optimization and MultivariateOptimizationResults.

- src/multivariate/solvers/constrained/fminbox.jl
- test/multivariate/solvers/constrained/constrained.jl
> Fix Fminbox annoyances.

- test/REQUIRE
- test/general/api.jl
- test/general/callbacks.jl
- test/general/counter.jl
- test/general/types.jl
- test/multivariate/lsthrow.jl
- test/multivariate/optimize/interface.jl
- test/multivariate/solvers/first_order/accelerated_gradient_descent.jl
- test/multivariate/solvers/first_order/cg.jl
- test/multivariate/solvers/first_order/momentum_gradient_descent.jl
- test/multivariate/solvers/first_order/ngmres.jl
- test/multivariate/solvers/second_order/krylov_trust_region.jl
- test/multivariate/solvers/second_order/newton.jl
- test/multivariate/solvers/second_order/newton_trust_region.jl
- test/multivariate/solvers/zeroth_order/nelder_mead.jl
- test/multivariate/solvers/zeroth_order/particle_swarm.jl
- test/runtests.jl
Update tests to work with https://github.com/JuliaNLSolvers/OptimTestProblems.jl/pull/9
(Whenever that's merged and OptimTestProblems ~2.0~ 1.2 is registered)
> Work with OptimTestProblems 1.2

- joss/Makefile
- joss/latex.template
- joss/paper.bib
- joss/paper.md
I submitted the repo to JOSS. We need the paper.md and paper.bib files to be stored on in the repo.
> Add JOSS paper

- joss/paper.md
Remove example usage and add URL
> Update JOSS paper

- joss/paper.bib
- joss/paper.md
This addresses the points of the editor and Abel Siqueira related to the JOSS paper. https://github.com/openjournals/joss-reviews/issues/615#issuecomment-372409437
Still to-do (would you be happy to add this later @pkofod ?)
- Document ParticleSwarm 
- Add "Contributiors.md" or similar
> JOSS update 

- docs/src/algo/newton.md
- src/multivariate/solvers/first_order/accelerated_gradient_descent.jl
- src/multivariate/solvers/first_order/bfgs.jl
- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
- src/multivariate/solvers/first_order/l_bfgs.jl
- src/multivariate/solvers/first_order/momentum_gradient_descent.jl
- src/multivariate/solvers/first_order/ngmres.jl
- src/multivariate/solvers/second_order/newton.jl
- src/utilities/generic.jl
- src/utilities/perform_linesearch.jl
- test/multivariate/lsthrow.jl
This works against LineSearches master.. Next up is univariate-izing line searches.
> Track LineSearches master.

- README.md
Let me know if this is okay, @pkofod
> Add JOSS badge and BiBTeX

- docs/make.jl
> Don't use relative directories for making docs

- test/multivariate/optimize/inplace.jl
- test/runtests.jl
(I realize that this file isn't included from `runtests.jl`)
> Test inplace keyword

- REQUIRE
Calculus is listed twice in REQUIRE
> Remove duplicate Calculus line

- docs/src/algo/ngmres.md
- src/multivariate/solvers/first_order/ngmres.jl
Ref https://github.com/JuliaNLSolvers/LineSearches.jl/pull/97
> NGMRES: Scale GD step length with InitialStatic

- src/multivariate/solvers/constrained/fminbox.jl
- src/multivariate/solvers/first_order/ngmres.jl
- test/multivariate/solvers/constrained/constrained.jl
.This PR also handles SingularException errors that I've been getting when using NGMRES with Fminbox.
> Enable NGMRES and OACCEL for Fminbox

- src/api.jl
- src/multivariate/solvers/constrained/fminbox.jl
- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/second_order/newton_trust_region.jl
- src/utilities/perform_linesearch.jl
- test/general/api.jl
- test/general/initial_convergence.jl
- test/multivariate/solvers/constrained/constrained.jl
- test/multivariate/solvers/constrained/fminbox.jl
- test/multivariate/solvers/first_order/cg.jl
- test/runtests.jl
Miscellaneous code enhancements/cleanups, mostly around Fminbox.
> Fminbox enhancements

- REQUIRE
- src/Optim.jl
- src/multivariate/solvers/constrained/ipnewton/interior.jl
- src/multivariate/solvers/constrained/ipnewton/iplinesearch.jl
- src/multivariate/solvers/constrained/ipnewton/ipnewton.jl
- src/multivariate/solvers/constrained/ipnewton/types.jl
- src/multivariate/solvers/constrained/ipnewton/utilities/assess_convergence.jl
- src/multivariate/solvers/constrained/ipnewton/utilities/trace.jl
- src/multivariate/solvers/constrained/ipnewton/utilities/update.jl
- test/multivariate/solvers/constrained/ipnewton/constraints.jl
- test/multivariate/solvers/constrained/ipnewton/counter.jl
- test/multivariate/solvers/constrained/ipnewton/ipnewton_unconstrained.jl
- test/multivariate/solvers/constrained/ipnewton/readme.jl
- test/runtests.jl
@anriseth do you know what's up with Fminbox and GMRES here? Check the log after the tests have run.
@timholy your work finally produces fruit. Thanks for the effort!
I'm not sure how to do it, but especially @timholy, but certainly also @anriseth deserve credit here. I'll see if I can add authors to the commit.
> Move IPNewton in from ConstrainedOptim.

- src/multivariate/solvers/first_order/ngmres.jl
- test/multivariate/solvers/first_order/ngmres.jl
Ref https://github.com/JuliaNLSolvers/Optim.jl/pull/613#pullrequestreview-126345524
> Fix InitialConstantChange in NGMRES

- src/multivariate/solvers/constrained/fminbox.jl
> Allow for Options in Fminbox

- src/multivariate/solvers/constrained/ipnewton/interior.jl
- src/multivariate/solvers/constrained/ipnewton/ipnewton.jl
- test/multivariate/solvers/constrained/ipnewton/counter.jl
- test/multivariate/solvers/constrained/ipnewton/ipnewton_unconstrained.jl
> Update comments for IPNewton

- .gitignore
- test/REQUIRE
Sorry, I should have remembered to add this as well in #634 ...
> Add Documenter to test/REQUIRE

- src/Optim.jl
(windows does not like my git setup)
> Add a simple docstring to Optim module to tell users where to find help.

- docs/src/examples/ipnewton_basics.jl
BLI (Bernt Lie) made me aware that we had a few typos/mistakes in the IPNewton example. @anriseth is this now correct?
(thanks Lie)
> Small typos

- src/multivariate/solvers/constrained/fminbox.jl
- test/multivariate/arbitrary_precision.jl
- test/runtests.jl
> Fix arbitrary element types for fminbox

- src/multivariate/solvers/constrained/fminbox.jl
- src/multivariate/solvers/second_order/newton_trust_region.jl
- src/multivariate/solvers/zeroth_order/nelder_mead.jl
- src/multivariate/solvers/zeroth_order/particle_swarm.jl
- src/multivariate/solvers/zeroth_order/simulated_annealing.jl
I'ved added docstrings for `NewtonTrustRegion`, `SimulatedAnnealing`, `ParticleSwarm` and `NelderMead`. Only `Fminbox` is still incomplete as I'm not sure of how it works.
> Added docstrings (#469)

- src/multivariate/solvers/zeroth_order/nelder_mead.jl
No substantial changes here. I just made a few simplifications in the code for NelderMead after looking at it.
> Fix typo and use dot-allocation for NelderMead

- docs/src/algo/precondition.md
Copy/pasting the preconditioning example didn't work. It works now.
> fix precond example

- NEWS.md
- src/Optim.jl
- src/multivariate/solvers/constrained/fminbox.jl
> Improve fminbox trace / verbose printing.

- docs/src/user/tipsandtricks.md
Update the docs on how to reuse computations in common between objective function, gradient and Hessian as required.
> docs to compute objective, grad and hess simultaneously

- docs/src/user/minimization.md
closes #693 for the optim part at least, still need to improve linesearchesjl
> Make it more clear how to control the optimizer when using Fminbox.

- src/types.jl
Useful as a reference from the REPL
> Add docstring to Options

- REQUIRE
- src/Optim.jl
- src/multivariate/optimize/interface.jl
- src/multivariate/solvers/constrained/fminbox.jl
Should fix https://github.com/JuliaNLSolvers/Optim.jl/issues/531
> Use FillArrays to handle scalar bounds in Fminbox.

- docs/src/user/config.md
- src/api.jl
- src/multivariate/optimize/optimize.jl
- src/multivariate/solvers/constrained/ipnewton/interior.jl
- src/multivariate/solvers/constrained/ipnewton/utilities/trace.jl
- src/multivariate/solvers/first_order/accelerated_gradient_descent.jl
- src/multivariate/solvers/first_order/bfgs.jl
- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
- src/multivariate/solvers/first_order/l_bfgs.jl
- src/multivariate/solvers/first_order/momentum_gradient_descent.jl
- src/multivariate/solvers/first_order/ngmres.jl
- src/multivariate/solvers/second_order/krylov_trust_region.jl
- src/multivariate/solvers/second_order/newton.jl
- src/multivariate/solvers/second_order/newton_trust_region.jl
- src/multivariate/solvers/zeroth_order/nelder_mead.jl
- src/multivariate/solvers/zeroth_order/zeroth_utils.jl
- src/types.jl
- src/utilities/trace.jl
- src/utilities/update.jl
fixes https://github.com/JuliaNLSolvers/Optim.jl/issues/678
fixes https://github.com/JuliaNLSolvers/Optim.jl/issues/700
> Improve trace with simplex and time additions.

- src/multivariate/optimize/optimize.jl
- src/multivariate/solvers/constrained/samin.jl
- src/multivariate/solvers/zeroth_order/simulated_annealing.jl
> Add trace to SAMIN and some small fixes to SimulatedAnnealing.

- src/api.jl
- src/multivariate/optimize/optimize.jl
- src/types.jl
- test/multivariate/optimize/optimize.jl
> add info on if time_limit reached

- src/Optim.jl
- src/multivariate/solvers/second_order/newton_trust_region.jl
- test/multivariate/solvers/second_order/newton_trust_region.jl
when the eigenvalues have extreme magnitude.
> Make sure that lambda is large enough to make Hessian positive definite

- .travis.yml
- src/multivariate/solvers/second_order/newton_trust_region.jl
- test/multivariate/solvers/second_order/newton_trust_region.jl
The will lead to NaNs in the gradient and Hessian which have to be handled explicitly.
> Handle Inf values in NewtonTrustRegion

- src/multivariate/optimize/optimize.jl
- test/multivariate/solvers/constrained/fminbox.jl
- test/runtests.jl
> Actually stop at line search failure

- src/univariate/solvers/brent.jl
- test/univariate/solvers/brent.jl
fixes https://github.com/JuliaNLSolvers/Optim.jl/issues/798
still need to add tests
> fix Brent for flat functions

- docs/src/examples/ipnewton_basics.jl
Okay, this PR doesn't exactly change the world or anything, but I saw it and thought I could help out. :smile:
> Fix typo in IPNewton docs

- Project.toml
I thought some more details on the callback function would be helpful.
> Update the documentation of the callback function. 

- test/multivariate/solvers/second_order/krylov_trust_region.jl
This goes with the PR https://github.com/JuliaNLSolvers/NLSolversBase.jl/pull/109 to NLSolverBase (and should only be merged after that PR has been merged); it allows the use of
* `only_fg_and_hv!(fg!, hv!)` and
* `only_fghv!(fghv!)` 
where
```
fg!(F, G, x) = (G === nothing || G .= ... ; F === nothing || return some_f(x))
hv!(Hv, x, v) = (Hv .= ...)
```
with Newton-Krylov.
Tests pass locally apart from 1 unrelated failure with LBFGS. 
closes #738 as far as I'm concerned.
> only_* constructors for newton-krylov

- src/multivariate/solvers/constrained/ipnewton/ipnewton.jl
- test/multivariate/solvers/constrained/ipnewton/interface.jl
- test/runtests.jl
> Make promote_obj noop for ipnewton and twicediffed

- docs/src/user/tipsandtricks.md
I was having some problems so went back to basics, but the code didn't run!
> Small typo in doc, code doesnt run without .+

- src/univariate/solvers/brent.jl
- test/univariate/solvers/brent.jl
- test/univariate/solvers/golden_section.jl
Fixes #867
I had forgotten an element in the named tuple.
> Test that tracing works for univariate optimization.

- src/multivariate/optimize/optimize.jl
- src/utilities/assess_convergence.jl
- src/utilities/maxdiff.jl
- src/utilities/trace.jl
With this, I can do:
```julia
julia> using Optim, CUDA
julia> init = CUDA.rand(10, 10);
julia> function fg!(_, G, w)
res = sum(abs2, w)
if !isnothing(G)
@. G = 2w
end
return res
end
fg! (generic function with 1 method)
julia> CUDA.allowscalar(false)
julia> optimize(Optim.only_fg!(fg!), init)
* Status: success
* Candidate solution
Final objective value:     0.000000e+00
* Found with
Algorithm:     L-BFGS
* Convergence measures
|x - x'|               = 9.90e-01 ≰ 0.0e+00
|x - x'|/|x'|          = Inf ≰ 0.0e+00
|f(x) - f(x')|         = 3.48e+01 ≰ 0.0e+00
|f(x) - f(x')|/|f(x')| = Inf ≰ 0.0e+00
|g(x)|                 = 0.00e+00 ≤ 1.0e-08
* Work counters
Seconds run:   5  (vs limit Inf)
Iterations:    1
f(x) calls:    3
∇f(x) calls:   3
```
> make some utils gpu friendly

- src/multivariate/solvers/first_order/l_bfgs.jl
- test/multivariate/solvers/constrained/fminbox.jl
> Fix reset of LBFGS.

- src/Optim.jl
- src/multivariate/precon.jl
- test/multivariate/precon.jl
I just define our own that falls back to LinearAlgebra's.
> Stop being a ☠️  (fix #900, ldiv! and dot pirates Base).

- src/multivariate/solvers/first_order/bfgs.jl
> Don't use turbo. All BFGS first calls will be 10 seconds slower.

- Project.toml
- test/Project.toml
- test/multivariate/array.jl
- test/multivariate/manifolds.jl
- test/multivariate/solvers/first_order/momentum_gradient_descent.jl
The change is to use StableRNGs instead of Random.seed!.
> Get tests passing on v1.7

- src/multivariate/optimize/optimize.jl
- src/multivariate/solvers/zeroth_order/nelder_mead.jl
Fixes #965
```
julia> optimize(x->x[1]^2, [4.0])
* Status: success
* Candidate solution
Final objective value:     3.187452e-09
* Found with
Algorithm:     Nelder-Mead
* Convergence measures
√(Σ(yᵢ-ȳ)²)/n ≤ 1.0e-08
* Work counters
Seconds run:   0  (vs limit Inf)
Iterations:    11
f(x) calls:    25
```
> Allow univariate nelder mead.

- src/multivariate/solvers/first_order/bfgs.jl
Given @vpuri3 won't be able to make the change I suggested here: https://github.com/JuliaNLSolvers/Optim.jl/pull/972#issuecomment-1027028046 for a few days:
> thanks @chriselrod , @pkofod . im unavailable for a few days due to travel. ill just do loop reordering for now, and leave it open for later improvements.
I figured I'd make it here.
> use muladd and hoist some multiplications

- src/multivariate/solvers/zeroth_order/particle_swarm.jl
In my case I saw a x4 speedup for a function of 530 variables.
> Use LinAlg to speed up particle swarm

- docs/make.jl
- docs/src/algo/adam_adamax.md
- src/multivariate/solvers/first_order/adam.jl
Reread the paper and realized where the optimization came from. The epsilon is outside sort
> Add docs for adam and adamax

- src/api.jl
- src/univariate/printing.jl
- src/univariate/solvers/brent.jl
- src/univariate/solvers/golden_section.jl
- src/univariate/types.jl
- test/univariate/solvers/brent.jl
- test/univariate/solvers/golden_section.jl
https://github.com/JuliaNLSolvers/Optim.jl/issues/949
> added time_limit for univariate optimization

- docs/src/user/minimization.md
- src/api.jl
- test/general/api.jl
> Minor improvements and bugfixes related to NelderMead

- docs/src/user/config.md
- src/types.jl
- test/general/optimize.jl
> Update Options documentation

- Project.toml
- src/Optim.jl
- src/multivariate/optimize/optimize.jl
- src/multivariate/solvers/constrained/fminbox.jl
- src/multivariate/solvers/constrained/ipnewton/interior.jl
- src/multivariate/solvers/constrained/samin.jl
- src/types.jl
- test/general/api.jl
An alternative to calling all the individual functions to check why it stopped.
> Implement EnumX termination codes

- src/multivariate/optimize/optimize.jl
- src/multivariate/solvers/constrained/ipnewton/interior.jl
- src/multivariate/solvers/zeroth_order/nelder_mead.jl
- test/multivariate/solvers/first_order/gradient_descent.jl
> Fix initial convergence

- README.md
- docs/src/algo/lbfgs.md
- src/multivariate/solvers/first_order/accelerated_gradient_descent.jl
- src/multivariate/solvers/first_order/bfgs.jl
- src/multivariate/solvers/first_order/cg.jl
- src/multivariate/solvers/first_order/gradient_descent.jl
- src/multivariate/solvers/first_order/l_bfgs.jl
- src/multivariate/solvers/first_order/momentum_gradient_descent.jl
- src/multivariate/solvers/first_order/ngmres.jl
- src/multivariate/solvers/second_order/newton.jl
- test/general/api.jl
- test/general/callbacks.jl
- test/general/convergence.jl
- test/multivariate/arbitrary_precision.jl
- test/multivariate/lsthrow.jl
- test/multivariate/solvers/first_order/ngmres.jl
The PR simplifies a few boolean expressions (`true &&`, `== true` and `== false`).
> Simplify boolean expressions
